#! /bin/bash

IMG_BASE="_MG_"

photo_rm() {
  if [ -z $1 ]; then
    echo "`usage`"
    echo "Error: Need at least one file to remove."
    exit 1
  fi
  for img in $@; do
    rm -f "$IMG_BASE$img.JPG"
    rm -f "$IMG_BASE$img.CR2"
  done;
}

photo_sort() {
  if [ -z $1 ]; then
    parent=""
  else
    parent="$1/"
  fi

  jpg=$parent"jpg"
  raw=$parent"raw"
  echo "raw $raw"
  echo "jpg $jpg"

  mkdir -p $jpg
  mkdir -p $raw

  echo "Moving *.JPG to $jpg"
  mv $parent*.JPG $jpg 2>/dev/null

  echo "Moving *.CR2 to $raw"
  mv $parent*.CR2 $raw 2>/dev/null
}

photo_mv() {
  if [ -z $1 ]; then
    echo "`usage`"
    echo "Error: need src directory"
    exit 1
  else
    srcdir=$1
  fi

  mkdir -p $srcdir

  if [[ ( -z $2 ) && ( -z $3) ]]; then
    mv $IMG_BASE* $srcdir
  else
    mv $IMG_BASE{$2..$3}* src
  fi

}

usage() {
  echo "usage: photos -rm img1 img2 ... imgN"
  echo "       photos -sort [--all] [source]"
  echo "       photos -mv src [lower_limit] [upper_limit]"
}

if [ "$1"  == "-sort" ]; then
  if [ "$2" == "--all" ]; then
    for dir in `ls $3`; do
      if [ -d $dir ]; then
        photo_sort $dir
      fi
    done;
  else
    photo_sort $2
  fi
elif [ "$1" ==  "-rm" ]; then
    photo_rm ${*:2} # all args except the first
elif [ "$1" ==  "-mv" ]; then
    photo_mv ${*:2} # all args except the first
else
  usage
fi
