#! /bin/bash

if [ -e $1 ]; then
  parent=$1
else
  parent=""
fi

jpg=$parent/jpg
raw=$parent/raw

mkdir -p $jpg
mkdir -p $raw

echo "Moving *.JPG to $jpg"
mv $parent/*.JPG $jpg 2>/dev/null

echo "Moving *.CR2 to $raw..."
mv $parent/*.CR2 $raw 2>/dev/null
